/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],

  darkMode: "class",

  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e0e2ff",
        "on-background": "#2e3040",
        "surface-container-high": "#dcdee4",
        "tertiary": "#7c3aed",
        "surface-bright": "#edeef4",
        "on-tertiary-fixed": "#2e1065",
        "on-surface": "#2e3040",
        "surface": "#e8eaf0",
        "inverse-primary": "#a5b4fc",
        "primary-container": "#818cf8",
        "secondary-container": "#d8dae6",
        "tertiary-fixed": "#ede9fe",
        "primary-fixed-dim": "#a5b4fc",
        "background": "#e8eaf0",
        "on-error-container": "#991b1b",
        "surface-variant": "#dcdee4",
        "surface-container-lowest": "#f0f2f8",
        "on-secondary-fixed": "#1a1b26",
        "on-secondary-fixed-variant": "#404252",
        "inverse-on-surface": "#e8eaf0",
        "surface-dim": "#d4d6dc",
        "secondary-fixed": "#d8dae6",
        "primary": "#6366f1",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#e0e2ff",
        "secondary-fixed-dim": "#b8baca",
        "on-tertiary-container": "#3b1f63",
        "tertiary-container": "#a78bfa",
        "outline-variant": "#d0d2dc",
        "error-container": "#fee2e2",
        "surface-container-highest": "#d6d8de",
        "on-tertiary-fixed-variant": "#5b21b6",
        "on-surface-variant": "#585a68",
        "secondary": "#6c6e7e",
        "tertiary-fixed-dim": "#c4b5fd",
        "error": "#dc2626",
        "surface-container-low": "#e5e7ed",
        "outline": "#8a8c9a",
        "inverse-surface": "#2e3040",
        "surface-tint": "#6366f1",
        "on-secondary-container": "#585a68",
        "on-primary-fixed-variant": "#4338ca",
        "on-primary-fixed": "#1e1b4b",
        "surface-container": "#e2e4ea",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
      },

      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },

  plugins: [],
};