/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],

  darkMode: "class",

  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e7d5c7",
        "on-background": "#1c1917",
        "surface-container-high": "#d6d3d1",
        "tertiary": "#cda37f",
        "surface-bright": "#fafaf9",
        "on-tertiary-fixed": "#38200c",
        "on-surface": "#1c1917",
        "surface": "#f5f5f4",
        "inverse-primary": "#e7d5c7",
        "primary-container": "#e7d5c7",
        "secondary-container": "#e7e5e4",
        "tertiary-fixed": "#e7d5c7",
        "primary-fixed-dim": "#cda37f",
        "background": "#f5f5f4",
        "on-error-container": "#991b1b",
        "surface-variant": "#e7e5e4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1c1917",
        "on-secondary-fixed-variant": "#57534e",
        "inverse-on-surface": "#0a0908",
        "surface-dim": "#e7e5e4",
        "secondary-fixed": "#e7e5e4",
        "primary": "#8c6239",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#38200c",
        "secondary-fixed-dim": "#a8a29e",
        "on-tertiary-container": "#38200c",
        "tertiary-container": "#e7d5c7",
        "outline-variant": "#e7e5e4",
        "error-container": "#fee2e2",
        "surface-container-highest": "#d6d3d1",
        "on-tertiary-fixed-variant": "#704d2b",
        "on-surface-variant": "#57534e",
        "secondary": "#57534e",
        "tertiary-fixed-dim": "#cda37f",
        "error": "#dc2626",
        "surface-container-low": "#fafaf9",
        "outline": "#a8a29e",
        "inverse-surface": "#1c1917",
        "surface-tint": "#8c6239",
        "on-secondary-container": "#57534e",
        "on-primary-fixed-variant": "#704d2b",
        "on-primary-fixed": "#38200c",
        "surface-container": "#e7e5e4",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
      },

      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },

  plugins: [],
};