export const mockDashboardStats = {
  totalRevenue: { value: "$124,500", change: "+14.2%", isPositive: true },
  activeSellers: { value: "48", change: "+4 new", isPositive: true },
  pendingModeration: { value: "18", change: "-5 today", isPositive: true },
  totalOrders: { value: "1,240", change: "+8.5%", isPositive: true },
};

export const mockRevenueChartData = [
  { month: "Jan", revenue: 42000, orders: 410 },
  { month: "Feb", revenue: 58000, orders: 520 },
  { month: "Mar", revenue: 64000, orders: 610 },
  { month: "Apr", revenue: 81000, orders: 780 },
  { month: "May", revenue: 95000, orders: 890 },
  { month: "Jun", revenue: 110000, orders: 1050 },
  { month: "Jul", revenue: 124500, orders: 1240 },
];

export const mockNotifications = [
  {
    id: "NOTIF-1",
    title: "New Seller Registration",
    message: "Nordic Living Essentials submitted identity & tax verification documents.",
    time: "10 mins ago",
    read: false,
    type: "info",
  },
  {
    id: "NOTIF-2",
    title: "High AI Confidence Match",
    message: "Velvet Modular Sofa scored 98.4% quality confidence.",
    time: "45 mins ago",
    read: false,
    type: "success",
  },
  {
    id: "NOTIF-3",
    title: "Payout Completed",
    message: "May 2026 payout of $1,488 transferred to Urban WoodenCrafts.",
    time: "2 hours ago",
    read: true,
    type: "success",
  },
  {
    id: "NOTIF-4",
    title: "Low Stock Warning",
    message: "Cairo Furniture Hub has 3 items running low on inventory.",
    time: "5 hours ago",
    read: true,
    type: "warning",
  },
];

export const mockSellers = [
  {
    id: "SEL-001",
    name: "Urban WoodenCrafts",
    email: "contact@woodencrafts.com",
    phone: "+20 100 123 4567",
    storeUrl: "https://woodencrafts.com",
    address: "12 El-Tahrir Sq, Cairo, Egypt",
    productsCount: 142,
    commissionRate: 12,
    status: "Verified",
    totalSales: "$34,200",
    joinedDate: "2025-01-15",
    taxId: "TAX-994821",
    bankAccount: "**** **** **** 4819 (CIB Bank)",
  },
  {
    id: "SEL-002",
    name: "Modern Home Studio",
    email: "info@modernhomestudio.com",
    phone: "+20 111 987 6543",
    storeUrl: "https://modernhomestudio.com",
    address: "45 Road 9, Maadi, Cairo, Egypt",
    productsCount: 89,
    commissionRate: 10,
    status: "Verified",
    totalSales: "$28,150",
    joinedDate: "2025-02-01",
    taxId: "TAX-772109",
    bankAccount: "**** **** **** 1024 (QNB Alahli)",
  },
  {
    id: "SEL-003",
    name: "Nordic Living Essentials",
    email: "support@nordicliving.io",
    phone: "+20 122 345 6789",
    storeUrl: "https://nordicliving.io",
    address: "88 Abbas El-Akkad, Nasr City, Cairo",
    productsCount: 64,
    commissionRate: 15,
    status: "Pending Verification",
    totalSales: "$12,400",
    joinedDate: "2025-04-10",
    taxId: "TAX-334182",
    bankAccount: "**** **** **** 9912 (HSBC)",
  },
  {
    id: "SEL-004",
    name: "Cairo Furniture Hub",
    email: "sales@cairofurniture.eg",
    phone: "+20 109 876 5432",
    storeUrl: "https://cairofurniture.eg",
    address: "Building 4, Smart Village, Giza",
    productsCount: 210,
    commissionRate: 10,
    status: "Verified",
    totalSales: "$49,800",
    joinedDate: "2024-11-20",
    taxId: "TAX-110293",
    bankAccount: "**** **** **** 5543 (Banque Misr)",
  },
  {
    id: "SEL-005",
    name: "Minimalist Decors",
    email: "hello@minimalistdecors.com",
    phone: "+20 155 432 1098",
    storeUrl: "https://minimalistdecors.com",
    address: "15 El-Gezira St, Zamalek, Cairo",
    productsCount: 35,
    commissionRate: 12,
    status: "Suspended",
    totalSales: "$3,100",
    joinedDate: "2025-05-02",
    taxId: "TAX-883712",
    bankAccount: "**** **** **** 3321 (AlexBank)",
  },
];

export const mockCommissions = [
  {
    id: "COM-8901",
    sellerName: "Urban WoodenCrafts",
    sellerId: "SEL-001",
    period: "May 2026",
    month: "May",
    year: "2026",
    grossSales: "$12,400",
    commissionRate: "12%",
    earnedCommission: "$1,488",
    payoutStatus: "Paid",
    payoutDate: "2026-06-01",
    transactionsCount: 28,
  },
  {
    id: "COM-8902",
    sellerName: "Modern Home Studio",
    sellerId: "SEL-002",
    period: "May 2026",
    month: "May",
    year: "2026",
    grossSales: "$9,800",
    commissionRate: "10%",
    earnedCommission: "$980",
    payoutStatus: "Paid",
    payoutDate: "2026-06-01",
    transactionsCount: 19,
  },
  {
    id: "COM-8903",
    sellerName: "Cairo Furniture Hub",
    sellerId: "SEL-004",
    period: "May 2026",
    month: "May",
    year: "2026",
    grossSales: "$18,500",
    commissionRate: "10%",
    earnedCommission: "$1,850",
    payoutStatus: "Pending",
    payoutDate: "Scheduled Jun 15",
    transactionsCount: 42,
  },
  {
    id: "COM-8904",
    sellerName: "Nordic Living Essentials",
    sellerId: "SEL-003",
    period: "May 2026",
    month: "May",
    year: "2026",
    grossSales: "$4,200",
    commissionRate: "15%",
    earnedCommission: "$630",
    payoutStatus: "Processing",
    payoutDate: "In Transit",
    transactionsCount: 9,
  },
];

export const mockModerationQueue = [
  {
    id: "MOD-101",
    productTitle: "Nordic Minimalist Oak Dining Table",
    sellerName: "Nordic Living Essentials",
    category: "Dining Table",
    price: "$450",
    aiConfidence: "94%",
    qualityScore: "A+",
    submittedDate: "2026-07-28",
    status: "Pending Review",
    images: [
      "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80",
    ],
    imageUrl: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=300&auto=format&fit=crop&q=80",
    description: "Handcrafted natural oak dining table designed for modern minimalist interiors.",
    dimensions: "180 x 90 x 75 cm",
    material: "Solid Oak Wood",
    style: "Scandinavian / Minimalist",
  },
  {
    id: "MOD-102",
    productTitle: "Velvet Modular L-Shaped Sectional Sofa",
    sellerName: "Modern Home Studio",
    category: "Sofa",
    price: "$1,200",
    aiConfidence: "88%",
    qualityScore: "A",
    submittedDate: "2026-07-29",
    status: "Pending Review",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&auto=format&fit=crop&q=80",
    ],
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&auto=format&fit=crop&q=80",
    description: "Plush velvet modular couch with deep seating and custom corner configuration.",
    dimensions: "260 x 160 x 85 cm",
    material: "Velvet Fabric & Beechwood Frame",
    style: "Modern Contemporary",
  },
  {
    id: "MOD-103",
    productTitle: "Industrial Matte Black Floor Lamp",
    sellerName: "Urban WoodenCrafts",
    category: "Lighting",
    price: "$180",
    aiConfidence: "97%",
    qualityScore: "A+",
    submittedDate: "2026-07-30",
    status: "Pending Review",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80",
    ],
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&auto=format&fit=crop&q=80",
    description: "Adjustable arch floor lamp with powder-coated steel finish and warm LED bulb.",
    dimensions: "35 x 35 x 170 cm",
    material: "Matte Powder-Coated Steel",
    style: "Industrial Loft",
  },
  {
    id: "MOD-104",
    productTitle: "Ergonomic Mesh Executive Office Chair",
    sellerName: "Cairo Furniture Hub",
    category: "Office",
    price: "$290",
    aiConfidence: "79%",
    qualityScore: "B+",
    submittedDate: "2026-07-31",
    status: "Flagged Issues",
    images: [
      "https://images.unsplash.com/photo-1580481072645-022f9a6d1270?w=600&auto=format&fit=crop&q=80",
    ],
    imageUrl: "https://images.unsplash.com/photo-1580481072645-022f9a6d1270?w=300&auto=format&fit=crop&q=80",
    description: "High-back mesh chair featuring lumbar support adjustments and 3D armrests.",
    dimensions: "65 x 65 x 120 cm",
    material: "Breathable Mesh & Aluminum Base",
    style: "Ergonomic Workstation",
  },
];

export const mockOrders = [
  {
    id: "ORD-9901",
    customerName: "Amr Hassan",
    customerEmail: "amr.hassan@example.com",
    customerPhone: "+20 100 555 1234",
    sellerName: "Urban WoodenCrafts",
    itemsCount: 3,
    totalAmount: "$850",
    status: "Completed",
    date: "2026-08-01",
    shippingAddress: "Building 12, Road 250, Digla, Maadi, Cairo",
    paymentMethod: "Visa ending in 4242",
    items: [
      { name: "Oak Side Table", qty: 2, price: "$200" },
      { name: "Minimalist Wall Mirror", qty: 1, price: "$450" },
    ],
    timeline: [
      { status: "Order Placed", date: "2026-08-01 10:30 AM", done: true },
      { status: "Confirmed by Seller", date: "2026-08-01 11:15 AM", done: true },
      { status: "Shipped via Courier", date: "2026-08-01 02:00 PM", done: true },
      { status: "Delivered", date: "2026-08-01 06:45 PM", done: true },
    ],
  },
  {
    id: "ORD-9902",
    customerName: "Sarah Al-Mansoori",
    customerEmail: "sarah.mansoori@example.com",
    customerPhone: "+20 112 444 9876",
    sellerName: "Modern Home Studio",
    itemsCount: 1,
    totalAmount: "$1,200",
    status: "Processing",
    date: "2026-08-01",
    shippingAddress: "Villa 45, District 1, 5th Settlement, New Cairo",
    paymentMethod: "Mastercard ending in 8812",
    items: [{ name: "Velvet Modular L-Shaped Sectional Sofa", qty: 1, price: "$1,200" }],
    timeline: [
      { status: "Order Placed", date: "2026-08-01 01:10 PM", done: true },
      { status: "Confirmed by Seller", date: "2026-08-01 01:40 PM", done: true },
      { status: "In Production / Packing", date: "2026-08-01 03:00 PM", done: true },
      { status: "Out for Delivery", date: "Pending", done: false },
    ],
  },
  {
    id: "ORD-9903",
    customerName: "Khaled Zaki",
    customerEmail: "khaled.zaki@example.com",
    customerPhone: "+20 120 777 3344",
    sellerName: "Cairo Furniture Hub",
    itemsCount: 2,
    totalAmount: "$420",
    status: "Shipped",
    date: "2026-07-31",
    shippingAddress: "Apartment 7, 14 Gezira St, Zamalek, Cairo",
    paymentMethod: "Stripe Online Payment",
    items: [
      { name: "Ergonomic Mesh Chair", qty: 1, price: "$290" },
      { name: "Under-desk Footrest", qty: 1, price: "$130" },
    ],
    timeline: [
      { status: "Order Placed", date: "2026-07-31 09:00 AM", done: true },
      { status: "Confirmed by Seller", date: "2026-07-31 09:30 AM", done: true },
      { status: "Handed over to Aramex", date: "2026-07-31 04:00 PM", done: true },
      { status: "Delivered", date: "Pending", done: false },
    ],
  },
  {
    id: "ORD-9904",
    customerName: "Nouran Mahmoud",
    customerEmail: "nouran.m@example.com",
    customerPhone: "+20 106 222 8899",
    sellerName: "Nordic Living Essentials",
    itemsCount: 4,
    totalAmount: "$640",
    status: "Pending",
    date: "2026-07-30",
    shippingAddress: "Block 12, El-Rehab City, Cairo",
    paymentMethod: "Cash on Delivery",
    items: [
      { name: "Pendant Ceiling Light", qty: 2, price: "$200" },
      { name: "Ceramic Vase Set", qty: 2, price: "$120" },
    ],
    timeline: [
      { status: "Order Placed", date: "2026-07-30 08:20 PM", done: true },
      { status: "Awaiting Seller Confirmation", date: "Pending", done: false },
    ],
  },
];

export const mockRecentActivities = [
  { id: 1, title: "New Seller Application", desc: "Nordic Living submitted verification docs", time: "10 mins ago" },
  { id: 2, title: "Product Approved", desc: "Velvet Modular L-Shaped Sectional passed AI review", time: "45 mins ago" },
  { id: 3, title: "Payout Triggered", desc: "May commission payout released to Urban WoodenCrafts", time: "2 hours ago" },
  { id: 4, title: "System Alert", desc: "Auto-moderation accuracy score updated to 98.4%", time: "5 hours ago" },
];
