import {
  Search,
  Plus,
  Trash2,
  Building2,
  Bell,
  User,
  Settings,
  LogOut,
  Pencil,
  MapPin,
  ArrowRight,
  Sparkles,
  Camera,
  X,
  Mail,
  Calendar,
  Lock,
  Shield,
  Check,
  LayoutGrid,
  Laptop,
  Eye,
  EyeOff,
  CreditCard,
  CirclePlus,
  Zap,
  History,
  Languages,
  Share2,
  Globe,
  Moon,
  Sun,
  Coins,
  Database,
  Diamond,
  DoorOpen,
  Inbox,
  CheckCircle2,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Store,
  Truck,
  ExternalLink,
  Filter,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  Maximize2,
  Image,
  Play,
  RotateCcw,
  Minus,
  Star,
  Ruler,
  Palette,
  Hourglass,
} from "lucide-react";

const iconMap = {
  search: Search,
  add: Plus,
  remove: Minus,
  delete: Trash2,
  domain: Building2,
  notifications: Bell,
  person: User,
  settings: Settings,
  logout: LogOut,
  edit: Pencil,
  location_on: MapPin,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  photo_camera: Camera,
  close: X,
  mail: Mail,
  calendar_today: Calendar,
  lock: Lock,
  shield: Shield,
  check: Check,
  apps: LayoutGrid,
  laptop_mac: Laptop,
  visibility: Eye,
  visibility_off: EyeOff,
  payments: CreditCard,
  add_circle: CirclePlus,
  bolt: Zap,
  history: History,
  language: Languages,
  share: Share2,
  public: Globe,
  dark_mode: Moon,
  light_mode: Sun,
  token: Coins,
  database: Database,
  diamond: Diamond,
  meeting_room: DoorOpen,
  inbox: Inbox,
  check_circle: CheckCircle2,
  receipt_long: Receipt,
  shopping_cart: ShoppingCart,
  add_shopping_cart: ShoppingCart,
  remove_shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  store: Store,
  local_shipping: Truck,
  open_in_new: ExternalLink,
  filter_list: Filter,
  refresh: RefreshCw,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  maximize: Maximize2,
  image: Image,
  play_arrow: Play,
  rotate: RotateCcw,
  star: Star,
  straighten: Ruler,
  square_foot: Ruler,
  palette: Palette,
  hourglass_empty: Hourglass,
};

export default function Icon({ name, size = 24, className = "", ...props }) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} className={className} {...props} />;
}
